# Generated by Django 4.2.2 on 2023-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_created_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('PR', 'Происшествия'), ('POL', 'Политика'), ('SP', 'Спорт'), ('KU', 'Культура')], default='SP', max_length=3, verbose_name='Категория'),
        ),
    ]
